name: InfiniteJump
version: ${project.version}
author: MrMicky
description: The ultimate double jump / infinite jump plugin !
website: https://www.spigotmc.org/resources/inifinitejump.51522/
softdepend: [Spartan, AAC, NoCheatPlus]
main: fr.mrmicky.infinitejump.InfiniteJump
commands: 
  infinitejump:
    description: Toggle infinite jump or reload the config
    aliases: [ijump]
    usage: /<command> [toggle|reload]